# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/top.xdc

# IP: ip/fifo_sync_0/fifo_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_sync_0 || ORIG_REF_NAME==fifo_sync_0} -quiet] -quiet

# IP: ip/div_gen/div_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen || ORIG_REF_NAME==div_gen} -quiet] -quiet
