@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Mar 25 15:20:40 +0800 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Kalman_Iter_Unit_tb_behav -key {Behavioral:sim_1:Functional:Kalman_Iter_Unit_tb} -tclbatch Kalman_Iter_Unit_tb.tcl -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/cordic_arcsin_arccos_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/Kalman_Calculate_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/Kalman_Calibration_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/baud_gen_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/uart_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/uart_with_fifo_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/data_packing_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/test_uart_with_fifo_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/Kalman_Iter_Unit_tb_behav.wcfg -log simulate.log"
call xsim  Kalman_Iter_Unit_tb_behav -key {Behavioral:sim_1:Functional:Kalman_Iter_Unit_tb} -tclbatch Kalman_Iter_Unit_tb.tcl -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/cordic_arcsin_arccos_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/Kalman_Calculate_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/Kalman_Calibration_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/baud_gen_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/uart_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/uart_with_fifo_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/data_packing_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/test_uart_with_fifo_tb_behav.wcfg -view C:/Documents/Xilinx_project/FPGA/Pose_Detection_With_Kalman_Filter/Kalman_Iter_Unit_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
