/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.4 */
/* E:\lscc\diamond\3.8_x64\ispfpga\bin\nt64\scuba.exe -w -n rom_waveform -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type bram -wp 00 -rp 1100 -addr_width 8 -data_width 8 -num_rows 256 -outdata REGISTERED -cascade -1 -resetmode SYNC -sync_reset -memfile c:/users/22822/desktop/2/i2c_master_pcf8591_dac/rom_waveform.mem -memformat hex  */
/* Fri Dec 15 14:28:33 2017 */


`timescale 1 ns / 1 ps
module rom_waveform (Address, OutClock, OutClockEn, Reset, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] Address;
    input wire OutClock;
    input wire OutClockEn;
    input wire Reset;
    output wire [7:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam rom_waveform_0_0_0.INIT_DATA = "STATIC" ;
    defparam rom_waveform_0_0_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam rom_waveform_0_0_0.INITVAL_1F = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_1E = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_1D = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_1C = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_1B = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_1A = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_19 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_18 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_17 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_16 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_15 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_14 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_13 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_12 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_11 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_10 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_0F = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_0E = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_0D = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_0C = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_0B = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_0A = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_09 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_08 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam rom_waveform_0_0_0.INITVAL_07 = "0x0040400C080140C01C100241402C180341C03C200442404C280542C05C300643406C380743C07C40" ;
    defparam rom_waveform_0_0_0.INITVAL_06 = "0x0844408C480944C09C500A4540AC580B45C0BC600C4640CC680D46C0DC700E4740EC780F47C0FC80" ;
    defparam rom_waveform_0_0_0.INITVAL_05 = "0x1028310A871128B11A8F1229312A971329B13A9F142A314AA7152AB15AAF162B316AB7172BB17ABF" ;
    defparam rom_waveform_0_0_0.INITVAL_04 = "0x182C318AC7192CB19ACF1A2D31AAD71B2DB1BADF1C2E31CAE71D2EB1DAEF1E2F31EAF71F2FB1FAFF" ;
    defparam rom_waveform_0_0_0.INITVAL_03 = "0x1FAFB1F2F71EAF31E2EF1DAEB1D2E71CAE31C2DF1BADB1B2D71AAD31A2CF19ACB192C718AC3182BF" ;
    defparam rom_waveform_0_0_0.INITVAL_02 = "0x17ABB172B716AB3162AF15AAB152A714AA31429F13A9B1329712A931228F11A8B1128710A8310280" ;
    defparam rom_waveform_0_0_0.INITVAL_01 = "0x0FC7C0F4780EC740E4700DC6C0D4680CC640C4600BC5C0B4580AC540A45009C4C0944808C4408440" ;
    defparam rom_waveform_0_0_0.INITVAL_00 = "0x07C3C0743806C340643005C2C0542804C240442003C1C0341802C140241001C0C0140800C0400400" ;
    defparam rom_waveform_0_0_0.CSDECODE_B = "0b111" ;
    defparam rom_waveform_0_0_0.CSDECODE_A = "0b000" ;
    defparam rom_waveform_0_0_0.WRITEMODE_B = "NORMAL" ;
    defparam rom_waveform_0_0_0.WRITEMODE_A = "NORMAL" ;
    defparam rom_waveform_0_0_0.GSR = "ENABLED" ;
    defparam rom_waveform_0_0_0.RESETMODE = "SYNC" ;
    defparam rom_waveform_0_0_0.REGMODE_B = "NOREG" ;
    defparam rom_waveform_0_0_0.REGMODE_A = "OUTREG" ;
    defparam rom_waveform_0_0_0.DATA_WIDTH_B = 9 ;
    defparam rom_waveform_0_0_0.DATA_WIDTH_A = 9 ;
    DP8KC rom_waveform_0_0_0 (.DIA8(scuba_vlo), .DIA7(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), .DIA2(scuba_vlo), 
        .DIA1(scuba_vlo), .DIA0(scuba_vlo), .ADA12(scuba_vlo), .ADA11(scuba_vlo), 
        .ADA10(Address[7]), .ADA9(Address[6]), .ADA8(Address[5]), .ADA7(Address[4]), 
        .ADA6(Address[3]), .ADA5(Address[2]), .ADA4(Address[1]), .ADA3(Address[0]), 
        .ADA2(scuba_vlo), .ADA1(scuba_vlo), .ADA0(scuba_vhi), .CEA(OutClockEn), 
        .OCEA(OutClockEn), .CLKA(OutClock), .WEA(scuba_vlo), .CSA2(scuba_vlo), 
        .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), .DIB8(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), .DIB0(scuba_vlo), 
        .ADB12(scuba_vlo), .ADB11(scuba_vlo), .ADB10(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB8(scuba_vlo), .ADB7(scuba_vlo), .ADB6(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB4(scuba_vlo), .ADB3(scuba_vlo), .ADB2(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB0(scuba_vlo), .CEB(scuba_vhi), .OCEB(scuba_vhi), .CLKB(scuba_vlo), 
        .WEB(scuba_vlo), .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), 
        .RSTB(scuba_vlo), .DOA8(), .DOA7(Q[7]), .DOA6(Q[6]), .DOA5(Q[5]), 
        .DOA4(Q[4]), .DOA3(Q[3]), .DOA2(Q[2]), .DOA1(Q[1]), .DOA0(Q[0]), 
        .DOB8(), .DOB7(), .DOB6(), .DOB5(), .DOB4(), .DOB3(), .DOB2(), .DOB1(), 
        .DOB0())
             /* synthesis MEM_LPC_FILE="rom_waveform.lpc" */
             /* synthesis MEM_INIT_FILE="rom_waveform.mem" */;



    // exemplar begin
    // exemplar attribute rom_waveform_0_0_0 MEM_LPC_FILE rom_waveform.lpc
    // exemplar attribute rom_waveform_0_0_0 MEM_INIT_FILE rom_waveform.mem
    // exemplar end

endmodule
