/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.4 */
/* Fri Dec 15 14:28:33 2017 */

/* parameterized module instance */
rom_waveform __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), 
    .Q( ));
